update

diff --git a/emr-launch b/emr-launch
--- a/emr-launch
+++ b/emr-launch
@@ -1,13 +1,19 @@
 #!/bin/bash
 set -e
-trap cleanup INT
-cleanup() {
+trap cleanup_spinner `seq 0 15`
+trap cleanup_cluster INT
+cleanup_cluster() {
     if [ -n "$cluster_id" ]; then 
         echo "Terminating ... cluster ID: ${cluster_id}"; 
         aws2 emr terminate-clusters --cluster-ids "$cluster_id"
         sleep 5
     fi
     exit
+}
+cleanup_spinner() {
+    if [ -n "${spin_pid}" ]; then
+        kill -9 $spin_pid
+    fi
 }
 
 update_script_bucket(){
@@ -46,6 +52,18 @@ s3_create_bucket() {
         --region "${region}" \
         --create-bucket-configuration LocationConstraint="${region}"
 }
+spin() {
+  spinner="/|\\-/|\\-"
+  while :
+  do
+    for i in `seq 0 7`
+    do
+      echo -n "${spinner:$i:1}"
+      echo -en "\010"
+      sleep 1
+    done
+  done
+}
 
 # -------------––-------------- parsing arguments -----------------------------
 cluster_id=''
@@ -59,7 +77,7 @@ force='false'
 bootstrap_path='s3://dsc102-pa2-public/bootstrap-scripts/setup-common.sh'
 
 
-while getopts 'u:bf:vr:l:k:n:d:p:t' flag; do
+while getopts 'u:bfvr:l:k:n:d:p:t' flag; do
   case "${flag}" in
     u) pid="${OPTARG}" ;;
     b) spot='true' ;;
@@ -119,6 +137,16 @@ fi
 # -------------––--------------------------------------------------------------
 
 # -------------––-------------- spawning cluster ------------------------------
+
+id_list=list-clusters
+if [ -n "${id_list}" ]; then
+    echo "Warning: following cluster(s) is already running"
+    echo "$id_list"
+    if [ "${force}" = "false" ]; then
+        echo "Error: to spawn multiple clusters, set -f flag"
+        exit 1
+    fi
+fi
 emr_cluster=${pid}-emr-cluster
 if [ "$deploy" = 'true' ]; then
 
@@ -148,7 +176,7 @@ cluster_id=$(echo $ret | jq -r '.ClusterId')
 
 if [  -z "$cluster_id" ]; then
     echo "cluster failed to start"
-    exit
+    exit 1
 fi
 
 echo "Cluster starting ... cluster ID: ${cluster_id}"
@@ -156,20 +184,22 @@ echo "Cluster starting ... cluster ID: ${cluster_id}"
 
 sleep 20
 state=''
+spin &
+spin_pid=$!
 until [ "$state" = "WAITING" ]; do
     state=$(aws2 emr describe-cluster --cluster-id "${cluster_id}" | jq -r .Cluster.Status.State)
-    printf "Current cluster state: ${state}\r"
+    printf " Current cluster state: ${state}\r"
     if [[ ("${state}" = "TERMINATED") || ("${state}" = "TERMINATING") || ("${state}" = "TERMINATED_WITH_ERRORS") ]]; then
-        echo "Cluster terminated accidently. Check logs on AWS console."
+        echo " Cluster terminated accidently. Check logs on AWS console."
         break
     fi
-    sleep 20
+    sleep 5
 done
 
 if [ "$state" = "WAITING" ]; then
     printf "\nCluster is up\n"
 fi
-
+kill -9 $spin_pid
 ret=$(aws2 emr describe-cluster --cluster-id "${cluster_id}")
 dns_name=$(echo $ret | jq -r '.Cluster.MasterPublicDnsName')
 echo "Cluster specs: cluster id: ${cluster_id}, region: ${region}, instance type: ${instance_type}, worker number: ${num_worker}, spot option: ${spot}"
