update

diff --git a/emr-launch b/emr-launch
--- a/emr-launch
+++ b/emr-launch
@@ -12,46 +12,16 @@ cleanup_cluster() {
 }
 cleanup_spinner() {
     if [ -n "${spin_pid}" ]; then
-        kill -9 $spin_pid
+        pkill -9 $spin_pid
     fi
-}
-
-update_script_bucket(){
-    n=0
-    retrytime=3
-    until aws2 s3api head-bucket --bucket "$s3_bucket_scripts" 2>/dev/null; do
-        if [ $n -ge $retrytime ]; then
-            break
-        fi
-        ((++n))
-        echo "Bucket not up, retrying ..."
-        sleep 20
-    done
-
-    if [ $n -le $retrytime ]; then
-        aws2 s3api put-bucket-versioning --bucket "${s3_bucket_scripts}" --versioning-configuration Status=Enabled
-        aws2 s3 sync "s3://dsc102-pa2" "s3://${s3_bucket_scripts_folder}"
-    else
-        echo "Bucket not up, retry timeout"
-        exit 1
-    fi
-}
-
-s3_block_public() {
-    aws2 s3api put-public-access-block --bucket $1 \
-        --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
 }
 
 s3_check_exists() {
     aws2 s3api head-bucket --bucket "${1}"
 }
 
-s3_create_bucket() {
-    aws2 s3api create-bucket --acl private \
-        --bucket "${1}" \
-        --region "${region}" \
-        --create-bucket-configuration LocationConstraint="${region}"
-}
+
+
 spin() {
   spinner="/|\\-/|\\-"
   while :
@@ -68,14 +38,14 @@ spin() {
 # -------------––-------------- parsing arguments -----------------------------
 cluster_id=''
 spot='false'
-region='us-west-2'
-label='emr-5.28.0'
+region="${AWS_DEFAULT_REGION}"
+label="${EMR_DEFAULT_LABEL}"
 num_worker=4
 deploy='false'
 theia='false'
 force='false'
-bootstrap_path='s3://dsc102-pa2-public/bootstrap-scripts/setup-common.sh'
-
+bootstrap_path="${BOOTSTRAPE_PATH}"
+pid="${PID}"
 
 while getopts 'u:bfvr:l:k:n:dp:t' flag; do
   case "${flag}" in
@@ -96,8 +66,8 @@ while getopts 'u:bfvr:l:k:n:dp:t' flag; do
   esac
 done
 
-declare -a arr_name=('-p' '-k')
-declare -a arr=("$pid" "$key")
+declare -a arr_name=('-k')
+declare -a arr=("$key")
 
 for ((i=0;i<${#arr[@]};++i)); do
     if [ -z "${arr[i]}" ]; then
@@ -107,34 +77,18 @@ for ((i=0;i<${#arr[@]};++i)); do
 done
 # -------------––--------------------------------------------------------------
 
-# -------------––-------------- setting up bucket -----------------------------
-s3_bucket_logs=${pid}-emr-logs
-s3_bucket_scripts=${pid}-pa2
-s3_bucket_scripts_folder=${s3_bucket_scripts}/src
+# -------------––----------------- S3 checks ----------------------------------
 
-if [[ -n "$pid" ]]; then
-    if s3_check_exists "${s3_bucket_logs}"; then
-        echo "EMR logs bucket ${s3_bucket_logs} already exists, skipping"
-    else
-        echo "Creating emr logs bucket: ${s3_bucket_logs}"
-        s3_create_bucket "${s3_bucket_logs}"
-        s3_block_public "${s3_bucket_logs}"
+s3_bucket_logs=${pid}${S3_LOGS_POSTFIX}
+s3_bucket_scripts=${pid}${S3_PA2_POSTFIX}
+s3_bucket_scripts_folder=${s3_bucket_scripts}/${S3_PA2_SRC_FOLDER}
+s3_buckets=("${s3_bucket_logs}" "${s3_bucket_scripts}")
+for bucket in "${s3_buckets[@]}"; do
+    if !(s3_check_exists $bucket); then
+        echo "ERROR: S3 bucket of $bucket does not exist. Run s3-pa2-init first."
+        exit 1
     fi
-    if s3_check_exists "${s3_bucket_scripts}"; then
-        echo "Scripts bucket ${s3_bucket_scripts} already exists, updating the bucket with missing files"
-        update_script_bucket
-    else
-        echo "Creating scripts bucket: ${s3_bucket_scripts}"
-        s3_create_bucket "${s3_bucket_scripts}" &&
-        echo "Copying PA2 scripts ..."
-        update_script_bucket
-
-    fi
-else
-    echo "Argument error: pid"
-    exit 1
-fi
-# -------------––--------------------------------------------------------------
+done
 
 # -------------––-------------- spawning cluster ------------------------------
 
@@ -147,9 +101,8 @@ if [ -n "${id_list}" ]; then
         exit 1
     fi
 fi
-emr_cluster=${pid}-emr-cluster
+emr_cluster=${pid}${EMR_CLUSTER_POSTFIX}
 if [ "$deploy" = 'true' ]; then
-
     instance_type="m5.xlarge"
 else
     instance_type="m4.large"
@@ -160,8 +113,6 @@ if [ "$spot" = 'true' ]; then
 else
     instance_group_core="InstanceCount=$num_worker,InstanceType=$instance_type"    
 fi
-
-echo ${theia}
 
 ret=$(aws2 emr create-cluster \
 --release-label "${label}" \
@@ -183,10 +134,9 @@ fi
 
 echo "Cluster starting ... cluster ID: ${cluster_id}"
 
-
+spin &
 sleep 20
 state=''
-spin &
 spin_pid=$!
 until [ "$state" = "WAITING" ]; do
     state=$(aws2 emr describe-cluster --cluster-id "${cluster_id}" | jq -r .Cluster.Status.State)
@@ -202,6 +152,7 @@ if [ "$state" = "WAITING" ]; then
     printf "\nCluster is up\n"
 fi
 kill -9 $spin_pid
+spin_pid=''
 ret=$(aws2 emr describe-cluster --cluster-id "${cluster_id}")
 dns_name=$(echo $ret | jq -r '.Cluster.MasterPublicDnsName')
 echo "Cluster specs: cluster id: ${cluster_id}, region: ${region}, instance type: ${instance_type}, worker number: ${num_worker}, spot option: ${spot}"
